### ISSUE TITLE
Error in bdfactory

### ISSUE THREAD

**Issue by indounderground** [Screetsec/TheFatRat#192]
[*] In the backdoor module
[*] Checking if binary is supported
[*] Gathering file info
[*] Reading win32 entry instructions
Traceback (most recent call last):
  File "/usr/bin/backdoor-factory", line 62, in <module>
    class bdfMain():
  File "/usr/bin/backdoor-factory", line 610, in bdfMain
    result = supported_file.run_this()
  File "/usr/lib/python2.7/dist-packages/bdfactory/pebin.py", line 168, in run_this
    return self.patch_pe()
  File "/usr/lib/python2.7/dist-packages/bdfactory/pebin.py", line 1725, in patch_pe
    issupported = self.support_check()
  File "/usr/lib/python2.7/dist-packages/bdfactory/pebin.py", line 1447, in support_check
    targetFile.pe32_entry_instr()
  File "/usr/lib/python2.7/dist-packages/bdfactory/intel/intelCore.py", line 77, in pe32_entry_instr
    self.f.seek(self.flItms['LocOfEntryinCode'])
IOError: [Errno 22] Invalid argument
 There was a problem in the creation of your backdoor file using backdoor-factory
 One of the problable causes is that the EXE file you selected is not yet supported

What kind of exe that supported for this module?

**Comment by peterpt** [comment]
Backdoor factory is no longer supported by their maintainers .
Executables for windows 7 are not supported .
https://github.com/secretsquirrel/the-backdoor-factory
