### ISSUE TITLE
Failed to generate APK

### ISSUE THREAD

**Issue by FabioNevesRezende** [Screetsec/TheFatRat#276]
On the logs/apk.log:

> /usr/local/lib/site_ruby/2.3.0/bundler/spec_set.rb:91:in `block in materialize': Could not find rake-12.3.1 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/site_ruby/2.3.0/bundler/spec_set.rb:85:in `map!'
	from /usr/local/lib/site_ruby/2.3.0/bundler/spec_set.rb:85:in `materialize'
	from /usr/local/lib/site_ruby/2.3.0/bundler/definition.rb:171:in `specs'
	from /usr/local/lib/site_ruby/2.3.0/bundler/definition.rb:238:in `specs_for'
	from /usr/local/lib/site_ruby/2.3.0/bundler/definition.rb:227:in `requested_specs'
	from /usr/local/lib/site_ruby/2.3.0/bundler/runtime.rb:108:in `block in definition_method'
	from /usr/local/lib/site_ruby/2.3.0/bundler/runtime.rb:20:in `setup'
	from /usr/local/lib/site_ruby/2.3.0/bundler.rb:107:in `setup'
	from /usr/local/lib/site_ruby/2.3.0/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /opt/metasploit-framework/config/boot.rb:26:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /opt/metasploit-framework/lib/msfenv.rb:12:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/bin/msfvenom:18:in `require_deps'
	from /usr/local/bin/msfvenom:36:in `init_framework'
	from /usr/local/bin/msfvenom:55:in `framework'
	from /usr/local/bin/msfvenom:364:in `<main>'

But I already have Rake installed in my ruby dependencies

Ruby version:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

**Comment by FabioNevesRezende** [comment]
Problem solved, it was happening because of the way I installed metasploit.
I uninstalled it and reinstalled using the oficial installer here https://metasploit.com/download and now worked correctly.
