### ISSUE TITLE
cp: cannot stat  / rm: cannot remove

### ISSUE THREAD

**Issue by rielinux** [Screetsec/TheFatRat#47]
Hi i have got this problem on my kali rolling, i have tried to find the solution over the web but can not find the answer, help me.. here is my choice  [05]  Backdooring Original apk [Instagram, Line,etc].

W: /usr/bin/aapt: symbol lookup error: /usr/lib/i386-linux-gnu/android/libaapt.so.0: undefined symbol: _ZN7android12AssetManager12addAssetPathERKNS_7String8EPi
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [/usr/bin/aapt, p, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 103018, --version-name, 1.3.1, -F, /tmp/APKTOOL3270487503658159053.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/TheFatRat/output/original/res, -M, /root/TheFatRat/output/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [/usr/bin/aapt, p, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 103018, --version-name, 1.3.1, -F, /tmp/APKTOOL3270487503658159053.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/TheFatRat/output/original/res, -M, /root/TheFatRat/output/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 127): [/usr/bin/aapt, p, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 103018, --version-name, 1.3.1, -F, /tmp/APKTOOL3270487503658159053.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/TheFatRat/output/original/res, -M, /root/TheFatRat/output/original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
[*] Signing output/fatrat_backdoored.apk ..
[+] Infected file output/fatrat_backdoored.apk ready.

cp: cannot stat '/root/TheFatRat/output/output/fatrat_backdoored.apk': No such file or directory
java.io.FileNotFoundException: /root/TheFatRat/backdoored/apkembed.apk (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:145)
	at com.android.signapk.SignApk.main(SignApk.java:320)
rm: cannot remove 'backdoored/apkembed.apk': No such file or directory

**Comment by peterpt** [comment]
You error could be related to multiple things : 
- an invalid apk file (test if your original apk installs on an android device)
- ruby script dependencies not installed in ruby .

Fatrat uses this github ruby script to merge the rat apk file with your original apk .
https://github.com/xc0d3rz/metasploit-apk-embed-payload

Clone that specific git and test it independently from fatrat to see if works .

I am developing a new way for fatrat merge the apk files without using the current ruby script , the reason is if you use ruby script and its dependencies are not installed , then you will not able to compile your apk  file .

However , this new changes will take some time because i already had 4 days in it and i am still finding bugs witch i am trying to fix them .

**Comment by rielinux** [comment]
Hi @peterpt  , I've been trying to use your script independently, here the result:
( I think I'm going to wait for you to fix this bug )

Embed a Metasploit Payload in an Original .Apk File v0.2
[1] Generating msfvenom payload
[2] Signing payload
[3] Decomposing original APK
[4] Decomposing payload APK
[5] Locating onCreate() hook
[6] Copying payload files
[7] Loading MainActivity.smali and injecting payload
[+] Adding android.permission.ACCESS_WIFI_STATE
[+] Adding android.permission.CHANGE_WIFI_STATE
[+] Adding android.permission.ACCESS_COARSE_LOCATION
[+] Adding android.permission.ACCESS_FINE_LOCATION
[+] Adding android.permission.SEND_SMS
[+] Adding android.permission.RECEIVE_SMS
[+] Adding android.permission.RECORD_AUDIO
[+] Adding android.permission.CALL_PHONE
[+] Adding android.permission.READ_CONTACTS
[+] Adding android.permission.WRITE_CONTACTS
[+] Adding android.permission.RECORD_AUDIO
[+] Adding android.permission.WRITE_SETTINGS
[+] Adding android.permission.CAMERA
[+] Adding android.permission.READ_SMS
[+] Adding android.permission.SET_WALLPAPER
[+] Adding android.permission.READ_CALL_LOG
[+] Adding android.permission.WRITE_CALL_LOG
[8] Rebuilding karma.apk with metasploit payload
W: /usr/bin/aapt: symbol lookup error: /usr/lib/i386-linux-gnu/android/libaapt.so.0: undefined symbol: _ZN7android12AssetManager12addAssetPathERKNS_7String8EPi
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [/usr/bin/aapt, p, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 103018, --version-name, 1.3.1, -F, /tmp/APKTOOL6466934486496436525.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/QQR2KDE/original/res, -M, /tmp/QQR2KDE/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [/usr/bin/aapt, p, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 103018, --version-name, 1.3.1, -F, /tmp/APKTOOL6466934486496436525.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/QQR2KDE/original/res, -M, /tmp/QQR2KDE/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 127): [/usr/bin/aapt, p, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 103018, --version-name, 1.3.1, -F, /tmp/APKTOOL6466934486496436525.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/QQR2KDE/original/res, -M, /tmp/QQR2KDE/original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
[!] Upgrade apktool to the latest apktool.jar fixes the issue completely

**Comment by peterpt** [comment]
Try this , just to see if bypasses that error .
clone my git on a different directory : 
https://github.com/peterpt/TheFatRat
i made some changes in the setup installation that install all the tools needed for the script to work .

In here , fatrat using that specific ruby script does not compile because it can not find a place to inject the payload , i tested with latest firefox apk  , this happens i believe because mostly that new apks have some new protections .
Depending on the apk file you are using ,  you may get luck or not .
Test it out because the setup will install the latest apktool witch the script are requesting in that error .
That ruby script is calling apktool from your system , and by the way it looks it is an old version .
Let me know how it went .

**Comment by rielinux** [comment]
This what i do to fix this, but latter on there are new problem.
1. Reinstalling my kali rolling and upgrade everything
2. Get a fresh fatrat & it works, but here come another problem.
I got this notifications:

W: warning: string 'your_map_is_now_ready' has no default translation.
W: warning: string 'zoom' has no default translation.
[*] Signing /root/TheFatRat/output/fatrat_backdoored.apk ..
[+] Infected file /root/TheFatRat/output/fatrat_backdoored.apk ready.
File copied with success to : /root/TheFatRat/backdoored
Removing temporary files from output
Signing your APK file
 Your payload has been successfully embed with sign and is located here :
 /root/TheFatRat/backdoored/output/Apk_embed_backdoor.apk.

What should i do bro ? 
Thanks

**Comment by peterpt** [comment]
according to the log the payload was build  

Those errors happened because that apk structure is new and ruby script is unable to fix it .
However , you should be able to install the backdoor apk on an android .
check the folder /root/TheFatRat/backdoored/output/Apk_embed_backdoor.apk

Fatrat is not 100% , fatrat depends on other tools that were not upgraded yet to new structure and functionality of new APK files .

My advice to you is to create an apk with payload with even with those errors and select an ip on your local lan , then install the apk and try it .
Use fatrat metasploit listeners / android  , to see that when you open the apk file if the android device communicates with your computer and open a session .

try with others apk files not so much recent versions .
I am unable to remove those errors detected from the ruby script that do the job because i did not build it and i dont not have knowledge in ruby programming .

Do the tests with the compiled apk to see if it works .
